version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/services/postgres/Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=autoservice
      - POSTGRES_PASSWORD=paspaspas
      - POSTGRES_SCHEMA=profiles
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    build:
      context: .
      dockerfile: docker/services/app/Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/autoservice
      - SPRING_DATASOURSE_USERNAME=postgres
      - SPRING_DATASOURSE_PASSWORD=paspaspas
      - SPRING_DATASOURSE_HIKARI_SCHEMA=profiles
      - SPRING_FLYWAY_BASELINE-ON-MIGRATE=true
      - SPRING_FLYWAY_ENABLED=true
    image: 'app_autoservice'
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  db-data: