version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/services/postgres/Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=paspaspas
      - POSTGRES_DB=autoservice
    image: 'db_autoservice'
    volumes:
      - "db-data:/var/lib/postgresql/data"

  appProfiles:
    build:
      context: .
      dockerfile: docker/services/app/Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/autoservice
      - MICROSERVICES_ORDERSSERVICE_URL_ORDERS=http://appOrders:8081
      - MICROSERVICES_ORDERSSERVICE_URL_GET_ORDERS=api/orders
      - SPRING_DATASOURSE_USERNAME=postgres
      - SPRING_DATASOURSE_PASSWORD=paspaspas
      - SPRING_DATASOURSE_HIKARI_SCHEMA=profiles
      - SPRING_FLYWAY_BASELINE-ON-MIGRATE=true
      - SPRING_FLYWAY_ENABLED=true
    image: 'app_autoservice_profiles'
    ports:
      - 8080:8080
    depends_on:
      - postgres

  appOrders:
    build:
      context: ../orders
      dockerfile: docker/services/app/Dockerfile
    environment:
      - PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/autoservice
      - SPRING_DATASOURSE_USERNAME=postgres
      - SPRING_DATASOURSE_PASSWORD=paspaspas
      - SPRING_DATASOURSE_HIKARI_SCHEMA=orders
      - SPRING_FLYWAY_BASELINE-ON-MIGRATE=true
      - SPRING_FLYWAY_ENABLED=true
    image: 'app_autoservice_orders'
    ports:
      - 8081:8081
    depends_on:
      - appProfiles

volumes:
  db-data: