server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autoservice
    username: postgres
    password: paspaspas
    driverClassName: org.postgresql.Driver
    hikari:
      schema: profiles
  flyway:
    enabled: true
    baseline-on-migrate: true