ordersService:
  url:
    base: ${ORDERSSERVICE_URL_ORDERS:http://localhost:8081}
    get:
      orders: ${ORDERSSERVICE_URL_GET_ORDERS:/api/orders}

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autoservice
    username: ${SPRING_DATASOURSE_USERNAME:czzz}
    password: paspaspas
    driverClassName: org.postgresql.Driver
    hikari:
      schema: profiles
  flyway:
    enabled: true
    baseline-on-migrate: true