version: '3.8'
services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.development
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=autoservice
      - POSTGRES_PASSWORD=paspaspas
    volumes:
      - "db-data:/var/lib/postgresql/data"


  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/autoservice
      - JS_URL=http://localhost
    image: 'my-java-application'
    ports:
      - 80:80
    depends_on:
      - postgres

volumes:
  db-data: